# Generated by Django 4.2.5 on 2023-09-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hi', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.IntegerField(default=18, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobby',
            field=models.CharField(default='reading', max_length=255, verbose_name='爱好'),
        ),
        migrations.AddField(
            model_name='user',
            name='info',
            field=models.CharField(max_length=255, null=True, verbose_name='个人介绍'),
        ),
    ]
