# Generated by Django 4.2.5 on 2023-09-14 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hi', '0004_user_age_user_hobby_user_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=64, null=True, verbose_name='密码'),
        ),
    ]
