# Generated by Django 4.2.5 on 2023-09-20 03:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Hi', '0006_author_authordetail_publish_book_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 20, 11, 30, 20, 286924)),
        ),
    ]
