# Generated by Django 4.2.5 on 2023-09-20 05:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Hi', '0008_alter_user_register_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='publish_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='publish',
            name='email',
            field=models.EmailField(default='shenqing@gmail.com', max_length=254),
            preserve_default=False,
        ),
    ]
